### PR TITLE
Export format

### PR DESCRIPTION
**Pull request by chris-rudmin**
`format` was not exported however `formatFile` was export twice

### CODE REVIEW

**Comment by chris-rudmin** [comment]
This PR breaks formatter fallback behaviour. However I still believe that format should be exported somehow.

**Comment by megahertz** [comment]
@chris-rudmin Why do you want to export format function? Actually, formatFile is not exported, it's just a default value for a config. Most of the module exports are declared the same way only for better autocomplete.

**Comment by chris-rudmin** [comment]
I'm overriding the console transport.  I only want to modify a small behaviour, and leave the rest the same. Unfortunately the original uses `format()` which is not exported. A different but related issue, when overriding `transport.console` I have to reassign `transport.console.level` and `transport.console.format` which is not apparent from the readme. I find the structure of assigning attributes to functions unintuitive and unconventional.

**Comment by megahertz** [comment]
Thank you for the response. I'll think about this problem.

**Pull request closed without merging**
