### PR TITLE
Fix ms in transports. prepend ms by period

### PR DESCRIPTION
**Pull request by faern**
The same bug as in #46 existed in all the default transports. I assumed they all used the `{ms}` formatting tag, but obviously not. Now they do.

I also made a subjective style change. You may of course not agree about this one and I can revert it if so. In my experience time is usually formatted with colons between hours, minutes and seconds, but then a period before the subseconds: `{h}:{i}:{s}.{ms}`. For example showed in the gray box here about ISO 8601: https://en.wikipedia.org/wiki/ISO_8601#Times

### CODE REVIEW

**Comment by faern** [comment]
WARNING: I have not tested this myself locally yet. Since I have problems with my JS dev environment. So I hope that either the tests are extensive enough or that you maybe verify that this does what it should. I'll see if I can get it running locally soon.

**Comment by faern** [comment]
Err. This does not work as it is. I'm fixing it now.

**Comment by faern** [comment]
@megahertz Now it builds! Let's just see if you agree with the removal of tests (they on longer tested the functionality of a function, merely just the value of a constant more or less)

**Comment by megahertz** [comment]
Hi @faern . Thank you for the great PR. I've used a custom format function because it's faster than templates. But I just tried to run a simple speed test and I can see that a custom format function it only twice faster than data templates. I thought that the difference is much larger. So your version is preferable. Also I agree on date format.

**Pull request merged**
