### PR TITLE
Add UTC formatting

### PR DESCRIPTION
**Pull request by eyalap**
@megahertz It's a naive implementation but utc support is needed and missing in logs

### CODE REVIEW

**Comment by megahertz** [comment]
Thank you for the PR. I need some time to think whether this feature should be built-in or not. At this moment, I don't like the way how it's enabled. In some template like "{y}-{m}-{d} {h}:{i}:{s} {utc}" the utc flag seems a bit tricky opposite to other templates which are variables.

**Comment by eyalap** [comment]
I don't like this way either, but I needed to have for my electron project.
I wanted to include it in variables, but that wasn't the right place either. 
There should be an options object like you have for log level in transports where these settings will be

**Comment by megahertz** [comment]
@eyalap I thought about the problem and it seems that the most simpler and efficient way is to add `{iso}` template, which is replaced by `date.toISOString()`. Sure, it's less flexible but doesn't require to make configuration more complex or irrational. I'm going to implement this in the next week. What do you think on it?

**Comment by eyalap** [comment]
Sorry, took me a while to comment back, in my case i need the flexability to be aligned with all our other log files.
But i agree its less complicated and ok. 
Thanks for committing

**Comment by megahertz** [comment]
Your situation is quite rare. For such a situation it's better to use a custom function as `format` option.

**Pull request closed without merging**
